language: php

sudo: required

env:
  global:
    - CS=7.1

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

script:
  - if [ "${TRAVIS_PHP_VERSION:0:3}" = "$CS" ]; then COVERAGE='--coverage-text' ; else COVERAGE='--no-coverage'; fi
  - composer install -n --prefer-dist
  - bin/console doctrine:fixtures:load -n -e test
  - bin/phpunit $COVERAGE
